blank_issues_enabled: false
contact_links:
  - name: Question or help
    url: https://discord.gg/gTZwuHVnkD
    about: For usage questions and general help, please use Discussions instead of opening an issue.